version: '3.9'

services:
  api:
    container_name: food-api
    build:
      context: .
      target: <deployment-type> # e.g., development || production
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
    command: npm run start:<dev || prod> # e.g., development || production
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:17
    container_name: food-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: <username> #your postgres username
      POSTGRES_PASSWORD: <password> #your postgres password
      POSTGRES_DB: food_delivery
    volumes:
      - pgdata:/var/lib/postgresql/data
      # remove the below lines if u do not need any migration or data seeding.
      - ./db/migration.sql:/docker-entrypoint-initdb.d/1-migration.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

volumes:
  pgdata:
