version: '3.9'

services:
  api:
    container_name: food-api
    build:
      context: .
      target: <deployment-type> # e.g., development || production
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: food-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: <username> #your postgres username
      POSTGRES_PASSWORD: <password> #your postgres password
      POSTGRES_DB: food_delivery
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
